spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_user_management
    username: postgres
    password: your_password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secretKey: y1Z3H8Y3hUcqBdXOpSk9vOrIMBz8abqZihKfHQVp07K1cVZShZh9mGBWr8f+RvAP
  expiration: 3600000

server:
  port: 8089
